language: node_js
sudo: required
node_js:
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

install:
  - yarn

deploy:
  provider: npm
  email: lamo2k123@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    node: 8
    repo: lamo2k123/rein-loader

os:
  - linux